version: '4'
services:
  db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    healthcheck:
      test: [“CMD-SHELL”, “pg_isready”]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5435:5432"
    volumes:
      - ./_pgdata:/var/lib/postgresql/data
